name = "ordernote-prompt"
client_id = "your_api_key"
application_url = "your_vercel_url"
embedded = true

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = ["your_vercel_url/auth/callback"]

[webhooks]
api_version = "2024-01"

  [webhooks.privacy_compliance]
  customer_deletion_url = "your_vercel_url/webhooks/customers/redact"
  customer_data_request_url = "your_vercel_url/webhooks/customers/data_request"
  shop_deletion_url = "your_vercel_url/webhooks/shop/redact"

[extensions.theme]
handle = "ordernote-extension"

[app_proxy]
url = "your_vercel_url"
subpath = "ordernote-prompt"
prefix = "apps"
