# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Magic Notes"
client_id = "f10d792eb3503c22404125658dcafbc2"
application_url = "https://ordernote-prompt.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://ordernote-prompt.vercel.app/auth/callback",
  "https://ordernote-prompt.vercel.app/auth/shopify/callback",
  "https://ordernote-prompt.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2026-10"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://ordernote-prompt.vercel.app/webhooks/customers/redact"
  customer_data_request_url = "https://ordernote-prompt.vercel.app/webhooks/customers/data_request"
  shop_deletion_url = "https://ordernote-prompt.vercel.app/webhooks/shop/redact"

[extensions.theme]
handle = "ordernote-extension"

[app_proxy]
url = "https://ordernote-prompt.vercel.app"
subpath = "ordernote-prompt"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
